workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60

    environment:
      flutter: 3.13.9
      java: 17

    scripts:
      - name: Get packages
        script: |
          flutter pub get

      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - build/app/outputs/apk/release/app-release.apk
      - build/app/outputs/flutter-apk/app-release.apk
